import { AboutUs } from "@/components/organisms/aboutus/aboutus/AboutUs"
import Head from "next/head"

const AboutUsPage = () => {
    return (
        <>
            <Head>
                <title>About Us : AJR</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <AboutUs />
        </>
    )
}

export default AboutUsPage