import { ServicesView } from "@/components/organisms/services/services/ServicesView"
import Head from "next/head"

const ServicesPage = () => {
    return (
        <>
            <Head>
                <title>Services : AJR</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <ServicesView />
        </>
    )
}

export default ServicesPage